### ISSUE TITLE
403bypass burp ext

### ISSUE THREAD

**Issue by yogapabeangi** [sting8k/BurpSuite_403Bypasser#1]

**Comment by sting8k** [comment]
Can you give more detail of the issue?

**Comment by thisguy23** [comment]
does it make requests? if its making requests its not really passive.

**Comment by sting8k** [comment]
> does it make requests? if its making requests its not really passive.

Yes, it will make requests

**Comment by sting8k** [comment]
> For me it only works when I launch a passive scan manually.

By default, this scan task is enabled. So the extension will always run. You can try to check target scope, or your settings .

![passive](https://user-images.githubusercontent.com/11132081/99928645-9b527880-2d7c-11eb-8959-1dc2b25f13ac.PNG)
